### ISSUE TITLE
(March 30th) automatic sensor identification and categorization if possible

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#1]
this information would then be presented to the respective device owner to be completed manually

**Comment by ssgUPC** [comment]
@cjdcordeiro hi....still we are looking for the proper strategy to identify the sensors automatically....once we will get it, we will try to develop it and validate it.

**Comment by cjdcordeiro** [comment]
@ssgUPC sure. There's no rush for this one as it is marked as "next" in line to be added to a sprint. Take your time and please keep us updated by writing any news into this ticket comment section

**Comment by ssgUPC** [comment]
@cjdcordeiro Thank you dear....I'll keep updating...

**Comment by ssgUPC** [comment]
http://docs.opengeospatial.org/is/15-078r6/15-078r6.html

This is the API...which we can implement to the mF2C

**Comment by ssgUPC** [comment]
Dear @cjdcordeiro,

Before we implement the API in our use-cases, I want to make sure that, what are the essentials information and data, that we are planning to collect from the IoTs (more precisely - from the sensors) through the SensorThings API. So for that purpose, I created a sensor data model, which I'm going to share along with this message. So, please find the attachment and check it. If you have any queries or suggestions, then please feel free to ping me. 

I'll be happy to hear any comments and suggestions. Thanking you in advance. 

Best regards,
Souvik

**Comment by cjdcordeiro** [comment]
Hi @ssgUPC 

please get in touch with Eva asap, as she can update you on the plan we've just agreed on yesterday.

If I understood well, you can rely on SensorThings to catalog the existing sensors, but you won't be able to discover the sensors using SensorThings, cause no one will register them. So we are coming up with a list of sensors we plan to support in mF2C. Your categorizer needs to manually scan for those and then yes, if you want to can create a "Thing" for them, to categorize them.

Also be aware that an extra piece of software will be needed - the mF2C Sensor Drivers, which will abstract the communication between mf2c services and sensors. These drivers should make use of your categorization and respective sensors API to wrap a set of supported sensor actions in mf2c. Example: `mf2c-get-location` shall be translated, internally, to a GPS-specific **or** WiFi-specific call, depending on the sensor availability

**Comment by cjdcordeiro** [comment]
@ssgUPC once you get in touch with Eva, please make sure you paste here the list of sensors we are going to support for mf2c

**Comment by ssgUPC** [comment]
@cjdcordeiro sure...I'll

**Comment by ssgUPC** [comment]
#90 Use the RaspberryPi and Gateway as agents for UC1

**Comment by ssgUPC** [comment]
@all, if I'm not wrong for the UC-1 we are using the inclinometer as a sensor. So, as I said earlier...I'm working on the automatic identification of sensors in our system...but you know that it is quite tough to automatically identify all the participating sensors in the system...So, what I'm proposing that I'll try to make a way for automatically identify the inclinometer in our system...as it is working on LoRa, so I need to check that, how my code can be implemented to identify the inclinometer in an automatic way... In the meanwhile, we found that corresponding Gateway of the inclinometer should have an agent copy...So, I guess somehow, I'm depending on the ticket "#90 mF2C/mF2C Use the RaspberryPi and gateway as agents for UC1" ...so I'm waiting for resolving the ticket before I'll move on to test my code.

**Comment by eva6370** [comment]
The part of the sensors and actuators that are selected manually is done
![Captura de pantalla 2018-11-08 15.54.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1d738611e6a00132e04b9/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726956f37a28c8b279f21223415e5a50a945465b4ceee59b6be4e96625d91819e7c3685620956f47afb18a4ebe02eb288b4f83b5bad91a92e86f37fb99cd1e604a5a45d0b50877b29359c95ffc4ae44954a21b3f63e375377c418653.png)
