### ISSUE TITLE
list policies for the leader election

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#13]
Please list all the policies you'd like to see implemented when selecting a suitable leader/backup.

Adopt the following simplified example:

---

 - if there's no leader in the vicinity, and I am capable of being a leader ("suitable for leadership"), then I become a leader, not matter what
 - if there's already a leader, but I am also capable of being one, then I am marked as a "suitable for leadership"
 - if there's a leader but no backup, and I'm suitable for leadership, then I become the backup
 - I am suitable for leadership if I have a wireless NIC
 - I am suitable for leadership if I have more than 2GB of RAM

**Comment by ALEJANDROJ19** [comment]
This week i'm out of the office. I'll try to provide some feedback next week.

**Comment by cjdcordeiro** [comment]
from Antonio:

 - I am suitable for leadership if I have a wireless NIC  *OR*  I have more than 2GB of RAM  (but in case I’d prefer to choose a power supplied node)

**Comment by eva6370** [comment]
Regarding: if there's no leader in the vicinity, and I am capable of being a leader ("suitable for leadership"), then I become a leader, not matter what
We add the next policy:

When one device installs the agent, it has two flags (one the capacity of being a leader, and the other if it is a leader). At the beginning both are 0 (the one of the capability can be updated with of the policies proposed by Cris: connectivity, etc). 
At the beginning, an agent starts always scanning, if after a time (to determine) does not detect a leader, it puts its of leader’s flag to one and starts broadcasting

**Comment by ALEJANDROJ19** [comment]
As we have now implemented, if the Leader flag is not set (environment variable), the agent role by default is normal (a.k.a. agent). The policy block triggers the Flow Control Joining Policies (FCJP) component that triggers the other modules involved in the joining procedure (Discovery, Identification, CAUClient, Categorization and Policies). As we added in the last version of the component, now we are able to scan multiple times until a leader is found (or timeout defined by policy) and when the leader is down (via beacon, not for backup purposes or recovery (at least now)), starting again the scan mechanism to find a new leader. 

When the FCJP component triggers the Leader Protection Policies (LPP) component, if the Agent role is normal, it waits to be elected as backup by the leader (if capable by policy - TBD). If the role is Leader, it queries the topology (now by the allowed list of IPs in the environment variable) and select one agent (if available) to be the backup. The backup performs a keep-alive protocol to check if the leader is alive and when it detects a failure in the leader, triggers some components to be the leader (and select a new backup if there are enough agents capable and available). 

As I see, in my opinion:

First, we need to set the requirements to be a Leader (RAM, connectivity, mobility...). The list of requirements is then used to determine if a device is capable or not (by the leader or the agent itself). Let's call **Level 1 Requirements** or **Mandatory requirements to become Leader**.

A second list of requirements is also needed to sort the devices from the most suitable to less preferable. In a basic implementation, this can be the first device in the topology. Let's call **Level 2 Requirements** or **Optional requirements to become Leader**.

Then, the additional policies needed for each of the requirements in the proposed example by @cjdcordeiro can be the following:

```
if there's no leader in the vicinity, and I am capable of being a leader ("suitable for leadership"), then I become a leader, not matter what
```
Here the proposed policies are the amount of time that the agent scans/waits to become the leader.

```
if there's already a leader, but I am also capable of being one, then I am marked as a "suitable for leadership"
```
Yes.

```
if there's a leader but no backup, and I'm suitable for leadership, then I become the backup
```
Yes, but is the Leader that needs to select the backup.

```
I am suitable for leadership if I have a wireless NIC
I am suitable for leadership if I have more than 2GB of RAM
```
These requirements can be Level 1 requirements (mandatory). But we need to determine which components are critical to be a Leader (Level 1) and which are likeable to find in a Leader (Level 2).

**Comment by cjdcordeiro** [comment]
1st - investigate how frequent the leader election should be and how to implement
2nd - implement 1 level of req only (for now), using these policies

**Comment by ALEJANDROJ19** [comment]
Some notes before holidays about the discussion:
1) Leader election should be something that it's running always. (example: Cluster change the requirements to be the leader). Now the agent can become a leader IF 1. Setup flag at startup OR 2. Leader fails and Backup is promoted to become new Leader. We need to think a way to add this feature. I think that this is a different issue that we need to create.

2) Related with this issue, I need a list of specific items/requirements that a device needs to become a leader. As we decided in the last meeting, we are now only considering to have a Wireless NIC, more than 2GB of RAM and that there is no another Leader in the area. With this last condition, we assume that race condition can happen (two agents becoming Leader at the same time).

**Comment by ALEJANDROJ19** [comment]
With the previous notes, I consider the issue/task done. The list of policies to be capable of being a Leader are the following:

- Have a Wireless NIC (That is linked to the Discovery Module correctly and is capable of sending Beacons).
- Have more than 2GB of RAM (available or total).
- There is no other Leader in the area at the moment of the Election (but race condition can happen).
