### ISSUE TITLE
(March 10th) Leader election implementation

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#15]
Implement a new automated mechanism to elect a leader in an empty area OR in an already established area.

needs mF2C/ResourceManagement#13
needs https://github.com/mF2C/ResourceManagement/issues/23

**Comment by cjdcordeiro** [comment]
include the selection of a backup

**Comment by ALEJANDROJ19** [comment]
Leader Election (And backup) implementation done. 

Summary:

- Leader Election now has 4 modes (Passive, Automatic, By Failure, By reelection) implemented.
- Keepalive Protocol updated. Now only uses the common port (46050) via REST calls.
- Backup failure detection and recovery implemented.
- Leader failure detection improved (retry attempts to avoid false positives, timeouts introduced)
- Multiple backups allowed.
- Leader is continuously looking for new backups with dynamic topology.
- Leader and Backup now can be Agents again without stopping the Policies container.
- Code stabilised and optimised.

Remaining work (new tickets):

- Integration Review with all the RM modules (on promotion to Leader and demotion to Agent).
- Get real topology from device resource in CIMI/dataclay
- Testing all together

Some cool photos:

![Captura](https://user-images.githubusercontent.com/8056184/55880630-642c5500-5ba1-11e9-9cef-401b002bc114.PNG)
![Captura2](https://user-images.githubusercontent.com/8056184/55880631-64c4eb80-5ba1-11e9-8962-b915a515eb50.PNG)
