### ISSUE TITLE
(May 20th) synchronize cloud-fog CAUs

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#16]

**Comment by syc17** [comment]
I don't remember this issue mentioned at the meeting.  From what I can gather from UPC, the cloud CAU does exactly what the other CAUs do: you connect to it to get a certificate from the CA.  UPC said they will not be doing any further work on the CAU with regard to IT2 demo.  So what are we trying to synchronize?

**Comment by cjdcordeiro** [comment]
what does the CAU do? please list its functionalities here

**Comment by syc17** [comment]
I think you should ask UPC if you are referring to the CAU that UPC implemented for IT2 and which they want to keep frozen.  The one I am planning to develop (which will be like a separate branch from the UPC one) will (provisionally) provide operations for:
1) certificate request (existing method)
2) device authenticated (existing method)
3) access token request
4) public key search
5) access token validation
And as we are talking about key management here, there need to be a mechanism for synchronising the public key information.  But to re-iterate, this has nothing to do with the UPC implementation as they do not intend to use the certificate beyond what they do now.

**Comment by cjdcordeiro** [comment]
alright, but then you've answered your own question, the CAUs need sync

**Comment by syc17** [comment]
Not sure you have read my comments correctly.  The UPC version does not and as far as I know, their version is the one that mF2C plans to use in the it2 demo.  The one that I am developing is a spare tyre (a branch) and may not even be used.

**Comment by cjdcordeiro** [comment]
where did you get the idea that your version might not be used?

**Comment by syc17** [comment]
This is the impression that I have from my talk with UPC (Sarang and Pau).  They have no interest in any new development in the CAU as there is no plan to make further use of the Agent certificate after the CAU client established a TLS connection with the Leader.CAU.

**Comment by cjdcordeiro** [comment]
sure, that's for UPC. The same way I have no interest in re-using our CIMI resources for SixSq's business. But for mF2C, we plan to use your changes to the CAU

**Comment by syc17** [comment]
That's good to hear, at least some positive commitment here.

**Comment by syc17** [comment]
Discussed requirements with Anna (BSC) and got some suggestions back on using Dataclay for the job.  Need to experiment on my part

**Comment by syc17** [comment]
Update: I have decided to use a native noSQL database for storing the STFC CAU data as we are only dealing with a simple key:value pair (deviceID:x.509cert.pem)  DataClay may be too heavy duty for such an application.

**Comment by syc17** [comment]
The STFC CAU is built using Spring and runs a Gemfire Geode KV nosql database.  I need to set up the distributed nodes but in the meantime, there is a single CAU in the cloud available: https://213.205.14.13:55443/cau
The validate IDKey function does not do anything at the moment, I am waiting for UPC to give instructions on how this is done.  Also, I need UPC to stop truncating the Agent deviceID to 64 chars and to pass the full deviceID to the CAU-Client when requesting a certificate.

**Comment by syc17** [comment]
Progress update: now able to run two separate client cache applications on two machines connected to a data cluster split between the two machines.   The cluster contains 2 servers and 3 locators.  The clients and backend cluster is connected in a client-server topology with the clients running a local caching proxy (near-cache data policy) to minimise latency.  The server nodes replicate data between themselves and the data are persisted to local disk when the server node shuts down.  Next step is to containerise the client cache application.  The server nodes are deployed via a Spring Gemfire shell script.

**Comment by syc17** [comment]
Progress update: There are practical issues with testing the deployment of the (non-containerised) versions of the cluster on the engineering VMs.  I don't want to risk introducing unforeseen changes to the host env which cause runtime issues with the CA and CAU as happend in the first week of December.  In view of the limited time left in the project, I feel it safer not to proceed with this task.
