### ISSUE TITLE
(Feb 28th) make sure the resource manager is being used in the hello world app

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#17]
Needs mF2C/mF2C#105 
needs mF2C/mF2C#106 
needs mF2C/mF2C#107 
needs mF2C/mF2C#108

**Comment by ALEJANDROJ19** [comment]
Done.
![Captura.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b8face11a4ebc0012c103d1/125516c66e82c728ace21e0d46cb958a379791a8cda5fd53b652fa912a5265296b51fa2f7387e57be61a7a505c0e46ac415e5c42afafdb2bf4a42062c80d55b98e30063e937f03a6aa8318b500bf258b4a8db7be8949c7e83d37aa.PNG)
