### ISSUE TITLE
Define CIMI resource for Agent

### ISSUE THREAD

**Issue by aqueralt** [mF2C/ResourceManagement#23]
According to the requirements expressed by Discovery (creator of the resource) and other consumer components (Lifecycle, SLA, Data Management), it must contain the following fields:
- deviceID: String 
- deviceIP: String 
- leaderID: String 
- leaderIP: String 
- authenticated: bool
- connected: bool
- isLeader: bool
- backupIP: String
- childrenIPs: List(String)

**Comment by dgasull** [comment]
Implemented Agent model according to requirements in dataClay in PR https://github.com/mF2C/mF2C/pull/139

**Comment by ALEJANDROJ19** [comment]
I have created the CIMI resource "Agent" in the https://github.com/mF2C/cimi/tree/upc-agent branch. @cjdcordeiro can you please check if everything is okay or I'm missing something (It's the first time that I have created a CIMI resource)?

**Comment by aqueralt** [comment]
@rsucasas just noticed that 'childrenIPs' is of type String instead of list(String) in CIMI. Needs to be fixed.
