### ISSUE TITLE
move dynamic attr out of device into device-dynamic

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#26]
powerplugged

actuatorInfo

ethernetAddress

wifiAddress

**Comment by ssgUPC** [comment]
@cjdcordeiro , I can move the `powerplugged`, `ethernetAddress`, `wifiAddress` to `device-dynamic` but as I'm getting the `actuatorInfo` from the registration module, so probably, for me it is quite tough to move the `actuatorInfo` into the `device-dynamic`. But, if someone provides me with this information then I can easily move it to the `device-dynamic`
