### ISSUE TITLE
fall back into the vpn IP whenever a local IP cannot be found

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#30]

**Comment by ssgUPC** [comment]
fixed with the new res-cat version `latest-V2.0.20`

**Comment by ALEJANDROJ19** [comment]
will solve: https://github.com/mF2C/ResourceManagement/issues/44

**Comment by ssgUPC** [comment]
Solved!!!

**Comment by ssgUPC** [comment]
Fixed the bugs!! Now it is ready for further testing

**Comment by eva6370** [comment]
Done successfully connected with VPN
