### ISSUE TITLE
CAU-client change on iface call (deviceID)

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#35]
> Policy component stops truncating the deviceID but to provide it in full to the CAU-client when getting the Agent certificate.  The modification is required as I need to use the complete deviceID as the key to storing the Agent’s public key in the CAU.   The CAU-client will handle the truncation of the deviceID to 64 chars to make sure that it fits in the CN field in the X.509 certificate.  I am now nearly ready to release the code.  Could you please make the change at your end and let me know us know the new docker image version to use. -- Shirley

**Comment by syc17** [comment]
@ALEJANDROJ19  As Identification verifies the IDKey now, I have removed this from the call to the CAU-Client.  Policy needs to call CAU-client as follows:
`detectedLeaderID=0f848d8fb78cbe5615507ef5a198f660ac89a3ae03b95e79d4ebfb3466c20d54e9a5d9b9c41f88c782d1f67b32231d31b4fada8d2f9dd31a4d884681b784ec5a,deviceID=3b95e79d4ebfb3466c20d54e5615507ef5a198f660ac89a3ae03b95e79d4ebfb3466c20d54e9a5d9b9c41f88c782d1f67b32231d31b4fada8d2f9dd31a4d8846df0d7b5473b6d2aa80`

**Comment by ALEJANDROJ19** [comment]
Hi @syc17 , i was implementing the integration test of Policies when i noticed something strange is happening with the CAU-client when triggered. I'm receiving err1 as reply and here is the log from the container:

```
129635 [Thread-1] DEBUG eu.mf2c.security.cc.cau.CauClient  - Got deviceID: efgh78907890789078907890789078907890, leaderDID: abcd123456123456123456123456
129636 [Thread-1] DEBUG eu.mf2c.security.cc.cau.CauClient  - CAU-client getCert method called.....
129638 [Thread-1] ERROR eu.mf2c.security.cc.CCRequestHandler  - Error handling request : Error getting X509 cert : eu.mf2c.security.Exception.CauClientException: java.lang.StringIndexOutOfBoundsException: String index out of range: 63
129649 [Thread-1] DEBUG eu.mf2c.security.cc.CCRequestHandler  - CCRequest handler closing client connection ....
```
I was also trying with a dumb string as LeaderID and deviceID. Any idea on what could be happening?

**Comment by syc17** [comment]
Use an deviceID that is longer than 64 char, please.

**Comment by ALEJANDROJ19** [comment]
solved, thanks!
