### ISSUE TITLE
provide integration tests for Policies module

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#37]

**Comment by ALEJANDROJ19** [comment]
Test expected output:

```
mf2c@uiharu:~/Desktop/docker-compose/tests$ bash policies.sh 
 [PoliciesTests]  Starting...
 [PoliciesTests]  SUCCESS: Policies API working properly 
 [PoliciesTests]  INFO: imLeader=false, imBackup=false 
 [PoliciesTests]  SUCCESS: Policies leader role successfully received 
 [PoliciesTests]  SUCCESS: Policies backup role successfully received 
 [PoliciesTests]  SUCCESS: Agent resource created 
```

**Comment by ALEJANDROJ19** [comment]
PR accepted. docker-compose requires modification to expose the Policies component Port in order to test the integration from "outside". If run in the same network environment (i.e. as a container part of the project) there is no need to expose the ports.

**Comment by eva6370** [comment]
Pending PR

**Comment by ALEJANDROJ19** [comment]
> we must not touch the mf2c stack and its configurations just for the sake of the tests. If you want to reach out to your api then simply run the tests from inside a/the container, with exec

Done. [PR](https://github.com/mF2C/mF2C/pull/242) accepted. Issue solved.
