### ISSUE TITLE
categorize the type of agent

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ResourceManagement#4]
in addition to the current categorization attributes, also include which type of agent we are:
 - cloud, fog, micro-agent...

**Comment by ssgUPC** [comment]
Okay... But I need to check that, what are the possible way to add this info

**Comment by cjdcordeiro** [comment]
yes please do. There should be a way. After all, for each type of device we have a different installation (cloud agent, fog agent, micro-agent), so worst case scenario, we'll hardcode in the installation scripts which type of agent "this is"

**Comment by cjdcordeiro** [comment]
just missing the change in the CIMI spec

**Comment by cjdcordeiro** [comment]
@ssgUPC please make the PR with the change in CIMI and I'll review it

**Comment by ssgUPC** [comment]
@cjdcordeiro I modified the code and already built the docker image....I'd like to inform you that, this is available on docker-hub....
