### ISSUE TITLE
Scanning periodically

### ISSUE THREAD

**Issue by eva6370** [mF2C/ResourceManagement#7]
The scanning should run periodically to detect the leader in order to not miss beacons or when the connection to the leader is broken/lost, to discover the new leader. Previously, the scan is executed once.

**Comment by ALEJANDROJ19** [comment]
Done. Discovery try up to 5 times is there is a leader in the location. When the leader disconnects, discovery automatically scans for the new leader (or becomes the new leader if it's the backup).

Policies module updated to 0.1.7.
