### ISSUE TITLE
Identification fixed address for getting credentials (cloud deployment issue)

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#70]
https://github.com/mF2C/mF2C/pull/306#issuecomment-545819728
> I deployed mF2C as cloud in another machine, but still does't get the credentials. Looking into the Identification code, I just found this https://github.com/mF2C/Registration-Identification/blob/b42611552dedeae8b34359331e0f10ee6ecc9ef8/Identification%20Module/ResourceManagement/src/java/Identification/RegisterDevice.java#L18 in the registration procedure. That means that if the IP is not set dynamically, Identification it will always try to get credentials from our mF2C provider. @ALEJANDROJ19 

https://github.com/mF2C/mF2C/pull/306#issuecomment-545892043
> @ALEJANDROJ19 thanks for looking into it. Can you create a ticket for it? SO that at least we know this exists, it can we face it again in the future. For now let's just live with dashboard then @cjdcordeiro 

The workaround to this issue is to create a `.env` file with user and password registered in http://dashboard.mf2c-project.eu:800/registration.html as follows:

```bash
isLeader=False
isCloud=True
MF2C_CLOUD_AGENT=
PHY=
WIFI_DEV_FLAG=
usr=<username>
pwd=<password>
```

**Comment by eva6370** [comment]
@cjdcordeiro 

@alxjand 

UPC has been thinking a possible solution but it implies too much changes. For a cloud deployment for a use case we should deploy not only the mF2C cloud agent but also the VPN server, the dashboard, the CA, etc. Then, we propose to leave the current solution (workarround) for the deployment of a mF2C cloud agent in the use cases, that is:

1. To register in the mF2C provider in the current mF2C cloud deployment and obtain the credentials.

2. Create a .env file with user and password registered in http://dashboard.mf2c-project.eu:800/registration.html.
