### ISSUE TITLE
CAU leader updates authenticated agents

### ISSUE THREAD

**Issue by eva6370** [mF2C/ResourceManagement#8]
We have to update last workflow about discovery, because in step 7.2.1, we need that the CAU leader sends to DB/CIMI not only MAC address and True if it is authenticated, but also the deviceID.

requires #23

**Comment by eva6370** [comment]
![FlowControlJoiningPolicies.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bd1d738611e6a00132e04b9/125516c66e82c728ace21e0d46ce989534a18ca79bfbb04f8e52f99a204820432608aa287980f06af3006b1300051bff054a5556f9f0dd78f4e03f79820d0aee80655f74c03e17ffeed01fed13a632c91edbe2e3d7158abd7f37ed998e47341f001c88f95d30a19c4fce5dfe59ac.png)

**Comment by ALEJANDROJ19** [comment]
Code added to put the updated information in 7.2.1. We are waiting to restructure how we are going to store this information to be more clear and easy to use.

**Comment by ALEJANDROJ19** [comment]
I consider this issue solved and we need a new issue to create the CIMI resource or modify the existing ones.

**Comment by ALEJANDROJ19** [comment]
outdated with the actual architecture
