### ISSUE TITLE
agentType not correct in device resource

### ISSUE THREAD

**Issue by ALEJANDROJ19** [mF2C/ResourceManagement#80]
https://github.com/mF2C/ResourceManagement/blob/6aa0eac146eacbbb79aa9ec8539450c5a84a864d/Resource-Categorization/X86-new/device_static.py#L45-L53

Coordinate with @fcarp10 to check the expected strings into the device resource.

**Comment by ssgUPC** [comment]
Fixed!!! Uploaded the new docker-image uploaded the docker-images @trunk repo :> for agent - `resCatlatest-V2.0.30` & for microagent `resCatlatest-V2.0.27-arm`

**Comment by ALEJANDROJ19** [comment]
> Fixed!!! Uploaded the new docker-image uploaded the docker-images @trunk repo :> for agent - `resCatlatest-V2.0.30` & for microagent `resCatlatest-V2.0.27-arm`

@ssgUPC Please create the PR with the new image and test https://github.com/mF2C/mF2C/pull/327 again
